{ config, lib, pkgs, ... }:

{
  options = {
    modules.services.crafty.enable = 
      lib.mkEnableOption "enables minecraft server management";
  };

  config = lib.mkIf config.modules.services.crafty.enable {
    
    # Firewall Ports
    networking.firewall.allowedTCPPortRanges = [
      {from = 25565; to = 25600;} 
    ];

    # Crafty manager
    virtualisation.oci-containers.containers."crafty_container" = {
      image = "registry.gitlab.com/crafty-controller/crafty-4:latest";
      environment = {
        "TZ" = "Etc/UTC";
      };
      volumes = [
        "/home/paki/data/crafty/backups:/crafty/backups:rw"
        "/home/paki/data/crafty/logs:/crafty/logs:rw"
        "/home/paki/data/crafty/servers:/crafty/servers:rw"
        "/home/paki/data/crafty/app/config:/crafty/app/config:rw"
        "/home/paki/data/crafty/import:/crafty/import:rw"
      ];
      ports = [
        "8443:8443/tcp"               # HTTPS WebUI
        "8123:8123/tcp"               # Dynmap
        "19132:19132/udp"             # Bedrock
        "25500-25600:25500-25600"     # Java
      ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=crafty"
        "--network=crafty_default"
      ];
    };
    systemd.services."podman-crafty" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
        };
        after = [
          "podman-network-crafty_default.service"
        ];
        requires = [
          "podman-network-crafty_default.service"
        ];
        partOf = [
          "podman-compose-crafty-root.target"
        ];
        wantedBy = [
          "podman-compose-crafty-root.target"
        ];
    };

    # Networks
    systemd.services."podman-network-crafty_default" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f crafty_default";
      };
      script = ''
        podman network inspect crafty_default || podman network create crafty_default
      '';
      partOf = [ "podman-compose-crafty-root.target" ];
      wantedBy = [ "podman-compose-crafty-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-crafty-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };

  };

}